/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PlrRouteImport } from './routes/plr'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout_.success'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as PoliciesCookiePolicyRouteImport } from './routes/policies.cookie-policy'
import { Route as PoliciesDeliveryPolicyRouteImport } from './routes/policies.delivery-policy'
import { Route as PoliciesPrivacyPolicyRouteImport } from './routes/policies.privacy-policy'
import { Route as PoliciesRefundPolicyRouteImport } from './routes/policies.refund-policy'
import { Route as PoliciesTermsOfServiceRouteImport } from './routes/policies.terms-of-service'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlrRoute = PlrRouteImport.update({
  id: '/plr',
  path: '/plr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout_/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesCookiePolicyRoute = PoliciesCookiePolicyRouteImport.update({
  id: '/policies/cookie-policy',
  path: '/policies/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesDeliveryPolicyRoute = PoliciesDeliveryPolicyRouteImport.update({
  id: '/policies/delivery-policy',
  path: '/policies/delivery-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyPolicyRoute = PoliciesPrivacyPolicyRouteImport.update({
  id: '/policies/privacy-policy',
  path: '/policies/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundPolicyRoute = PoliciesRefundPolicyRouteImport.update({
  id: '/policies/refund-policy',
  path: '/policies/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsOfServiceRoute = PoliciesTermsOfServiceRouteImport.update({
  id: '/policies/terms-of-service',
  path: '/policies/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/plr': typeof PlrRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/policies/cookie-policy': typeof PoliciesCookiePolicyRoute
  '/policies/delivery-policy': typeof PoliciesDeliveryPolicyRoute
  '/policies/privacy-policy': typeof PoliciesPrivacyPolicyRoute
  '/policies/refund-policy': typeof PoliciesRefundPolicyRoute
  '/policies/terms-of-service': typeof PoliciesTermsOfServiceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/plr': typeof PlrRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/policies/cookie-policy': typeof PoliciesCookiePolicyRoute
  '/policies/delivery-policy': typeof PoliciesDeliveryPolicyRoute
  '/policies/privacy-policy': typeof PoliciesPrivacyPolicyRoute
  '/policies/refund-policy': typeof PoliciesRefundPolicyRoute
  '/policies/terms-of-service': typeof PoliciesTermsOfServiceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/plr': typeof PlrRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout_/success': typeof CheckoutSuccessRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/policies/cookie-policy': typeof PoliciesCookiePolicyRoute
  '/policies/delivery-policy': typeof PoliciesDeliveryPolicyRoute
  '/policies/privacy-policy': typeof PoliciesPrivacyPolicyRoute
  '/policies/refund-policy': typeof PoliciesRefundPolicyRoute
  '/policies/terms-of-service': typeof PoliciesTermsOfServiceRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/plr'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/success'
    | '/collections/$slug'
    | '/policies/cookie-policy'
    | '/policies/delivery-policy'
    | '/policies/privacy-policy'
    | '/policies/refund-policy'
    | '/policies/terms-of-service'
    | '/product/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/plr'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/success'
    | '/collections/$slug'
    | '/policies/cookie-policy'
    | '/policies/delivery-policy'
    | '/policies/privacy-policy'
    | '/policies/refund-policy'
    | '/policies/terms-of-service'
    | '/product/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/plr'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout_/success'
    | '/collections/$slug'
    | '/policies/cookie-policy'
    | '/policies/delivery-policy'
    | '/policies/privacy-policy'
    | '/policies/refund-policy'
    | '/policies/terms-of-service'
    | '/product/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FaqRoute: typeof FaqRoute
  PlrRoute: typeof PlrRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  PoliciesCookiePolicyRoute: typeof PoliciesCookiePolicyRoute
  PoliciesDeliveryPolicyRoute: typeof PoliciesDeliveryPolicyRoute
  PoliciesPrivacyPolicyRoute: typeof PoliciesPrivacyPolicyRoute
  PoliciesRefundPolicyRoute: typeof PoliciesRefundPolicyRoute
  PoliciesTermsOfServiceRoute: typeof PoliciesTermsOfServiceRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plr': {
      id: '/plr'
      path: '/plr'
      fullPath: '/plr'
      preLoaderRoute: typeof PlrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/success': {
      id: '/checkout_/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/cookie-policy': {
      id: '/policies/cookie-policy'
      path: '/policies/cookie-policy'
      fullPath: '/policies/cookie-policy'
      preLoaderRoute: typeof PoliciesCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/delivery-policy': {
      id: '/policies/delivery-policy'
      path: '/policies/delivery-policy'
      fullPath: '/policies/delivery-policy'
      preLoaderRoute: typeof PoliciesDeliveryPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy-policy': {
      id: '/policies/privacy-policy'
      path: '/policies/privacy-policy'
      fullPath: '/policies/privacy-policy'
      preLoaderRoute: typeof PoliciesPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/refund-policy': {
      id: '/policies/refund-policy'
      path: '/policies/refund-policy'
      fullPath: '/policies/refund-policy'
      preLoaderRoute: typeof PoliciesRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms-of-service': {
      id: '/policies/terms-of-service'
      path: '/policies/terms-of-service'
      fullPath: '/policies/terms-of-service'
      preLoaderRoute: typeof PoliciesTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FaqRoute: FaqRoute,
  PlrRoute: PlrRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  PoliciesCookiePolicyRoute: PoliciesCookiePolicyRoute,
  PoliciesDeliveryPolicyRoute: PoliciesDeliveryPolicyRoute,
  PoliciesPrivacyPolicyRoute: PoliciesPrivacyPolicyRoute,
  PoliciesRefundPolicyRoute: PoliciesRefundPolicyRoute,
  PoliciesTermsOfServiceRoute: PoliciesTermsOfServiceRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
